name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        
    - name: Golint
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: lint

    - name: Gosec
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: sec

    - name: Staticcheck
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: staticcheck

    - name: GoVet
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: vet

    - name: GoFmt
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: fmt

    - name: Test
      run: go test -race -v ./...
